// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPPf8EzRrOjT9G7AQFIPqSjZiM6vuiBw0',
    appId: '1:934237748606:web:b1943acfebe4a15894872f',
    messagingSenderId: '934237748606',
    projectId: 'veterinariaapp-3cc9c',
    authDomain: 'veterinariaapp-3cc9c.firebaseapp.com',
    storageBucket: 'veterinariaapp-3cc9c.appspot.com',
    measurementId: 'G-KHY6C2NKYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlsSTsn9_K0OpDaHXQcZ2GhqJu2j1HwU4',
    appId: '1:934237748606:android:e129f961d2c88eed94872f',
    messagingSenderId: '934237748606',
    projectId: 'veterinariaapp-3cc9c',
    storageBucket: 'veterinariaapp-3cc9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBefuBJQRkDWauNvAQ92nbNCNtuh5Jvaas',
    appId: '1:934237748606:ios:d23847bedf89405594872f',
    messagingSenderId: '934237748606',
    projectId: 'veterinariaapp-3cc9c',
    storageBucket: 'veterinariaapp-3cc9c.appspot.com',
    iosBundleId: 'com.example.veterinariaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBefuBJQRkDWauNvAQ92nbNCNtuh5Jvaas',
    appId: '1:934237748606:ios:16b7209d2615b19494872f',
    messagingSenderId: '934237748606',
    projectId: 'veterinariaapp-3cc9c',
    storageBucket: 'veterinariaapp-3cc9c.appspot.com',
    iosBundleId: 'com.example.veterinariaapp.RunnerTests',
  );
}
